remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Portfolio
description: >
  Reach out to me: paliwalyash987@gmail.com | https://github.com/YashPaliwal19 | https://www.linkedin.com/in/yashpaliwal19

#<img src="/assets/img/github_logo.png" alt="Octocat" style="width: 35px; height: auto;"/> [Link to another page](./another-page.html)
show_downloads: false
google_analytics: G-Y0E1E40VQE
